# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/ancora/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/samsung/gravitysmart/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/samsung/gravitysmart/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so \
    vendor/samsung/gravitysmart/proprietary/lib/libsecril-client.so:obj/lib/libsecril-client.so 

# Binaries
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/bin/rmt_storage:system/bin/rmt_storage

# Cameradata
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
	vendor/samsung/gravitysmart/proprietary/cameradata/datapattern_420sp_gt2.yuv:system/cameradata/datapattern_420sp_gt2.yuv \
    vendor/samsung/gravitysmart/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp_.yuv

# Adreno libs
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/samsung/gravitysmart/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/samsung/gravitysmart/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	vendor/samsung/ancora_tmo/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/samsung/gravitysmart/proprietary/lib/libgsl.so:system/lib/libgsl.so 

# HW libs
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/samsung/gravitysmart/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so

# Camera libs
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/lib/libActionShot.so:system/lib/libActionShot.so \
    vendor/samsung/gravitysmart/proprietary/lib/libPanoraMax1.so:system/lib/libPanoraMax1.so \
    vendor/samsung/gravitysmart/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
    vendor/samsung/gravitysmart/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/samsung/gravitysmart/proprietary/lib/libcaps.so:system/lib/libcaps.so \
    vendor/samsung/gravitysmart/proprietary/lib/libexif.so:system/lib/libexif.so \
    vendor/samsung/gravitysmart/proprietary/lib/libjpeg.so:system/lib/libjpeg.so \
    vendor/samsung/gravitysmart/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/gravitysmart/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/gravitysmart/proprietary/lib/libs3cjpeg.so:system/lib/libs3cjpeg.so \
    vendor/samsung/gravitysmart/proprietary/lib/libseccameraadaptor.so:system/lib/libseccameraadaptor.so 

# Media libs
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/lib/libmmipl.so:system/lib/libmmipl.so 
	
# Firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/bin/BCM4329B1_002.002.023.0746.0817.hcd:system/vendor/firmware/bcm4329.hcd \
    vendor/samsung/gravitysmart/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/samsung/gravitysmart/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw

# RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/gravitysmart/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/gravitysmart/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/gravitysmart/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/gravitysmart/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so

